urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

'Django url dispatch file for django_logistics project.'

#from django.conf.urls.defaults import *
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import include, handler404

from django.conf import settings

# Uncomment the next two lines to enable the admin (v.1.2.1):
# is used for developing
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'packages': ('django_logistics',)
}

handler500 = 'django_logistics.viewtools.views.page_under_develop'

urlpatterns = patterns('',

    (r'^tools/', include('django_logistics.viewtools.urls')),

    (r'^', include('django_logistics.startpage.urls')),
    # Language code explicit in the URL
    (r'^(\w\w)/', include('django_logistics.startpage.urls')),

    (r'^orders/', include('django_logistics.orders.urls')),
    # Language code explicit in the URL
    (r'^(\w\w)/orders/', include('django_logistics.orders.urls')),

    (r'^accounts/', include('django_logistics.registration.urls')),
    # Language code explicit in the URL
    (r'^(\w\w)/accounts/', include('django_logistics.registration.urls')),

    #(r'^clients/', include('django_logistics.testdrive.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # is used for developing
    #   (r'^admindks/(.*)', admin.site.root),  # Django v.1.0
    (r'^admindks/', include(admin.site.urls)), # Django v.1.2 or v.1.3


#    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^staticfiles/css/(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': settings.STATIC_DOC_ROOT + '/css',
                     'show_indexes': True}),
        (r'^staticfiles/js/(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': settings.STATIC_DOC_ROOT + '/js',
                     'show_indexes': True}),
        (r'^staticfiles/img/(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': settings.STATIC_DOC_ROOT + '/img',
                     'show_indexes':True}),
)

testdrive/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Client(models.Model):
    """ Includes information about clients firms """

    client_name = models.CharField(_('client name'), unique=True, max_length=50)
    address = models.CharField(_('address'), max_length=200)
    contact_person = models.CharField(_('contact person'), max_length=100)
    email = models.EmailField(_('e-mail address'), max_length=85, blank=True, default='')
    phone_number = models.CharField(_('phone number'), max_length=15, blank=True, default = '')


    def __unicode__(self):
        return self.client_name

class Order(models.Model):
    """ Includes order information """

    client = models.ForeignKey(Client, related_name=_('orders'))
    order_number = models.CharField(_('order number'), unique=True, max_length=30)
    from_address = models.CharField(_('address from'), max_length=200)
    to_address = models.CharField(_('address to'), max_length=200)    
    transp_date = models.DateField(_('Day of transport.'))
    weight = models.DecimalField(_('weight'), max_digits=5, decimal_places=2)
    comments = models.CharField(_('comments'), max_length = 200, default='', blank=True)

    def __unicode__(self):
        return self.order_number

class RemarksOrder(models.Model):
    """Information about order execution"""

    order = models.OneToOneField(Order, unique=True)
    exect = models.BooleanField()
    exect_date = models.DateTimeField('Day of execution')
    details = models.CharField(max_length = 200, default='')

    def __unicode__(self):
        return self.order.order_number + " Client: " + self.order.client.client_name

templates/clients/addclient.html
{% extends "infostatic/base_site.html" %}
{% load i18n %}

{% block content %}
    <div id="content-main">
        <form action="/clients/addclient/" method="post">            {{ form.as_p }}
            <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

templates/clients/addorder.html
{% extends "infostatic/base_site.html" %}
{% load i18n%}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="/staticfiles/css/forms.css" />
    <script type="text/javascript" src="{% url django.views.i18n.javascript_catalog %}"></script>
    <script type="text/javascript" src="/staticfiles/js/core.js"></script>
    <script type="text/javascript" src="/staticfiles/js/calendar.js"></script>
    <script type="text/javascript" src="/staticfiles/js/admin/DateTimeShortcuts.js"></script>
{% endblock %}

{% block content %}
    <div id="content-main">
        <form action="{{act}}" method="post">
            {{ form.as_p }}
            <p><input type="submit" value="Submit" /></p>
        </form>
    </div>
{% endblock %}

templates/clients/detail.html
{% extends "infostatic/base_site.html" %}
{% load i18n %}


{% block content %}
    <h1>{{ cl.client_name }}</h1>
    <ul>
    {% for order in cl.order_set.all %}
         <li>{{order.order_number}} Date: {{order.transp_date}}</li>
    {% endfor %}
    </ul>
    <a href="{{act}}">Add order</a>
{% endblock %}

templates/clients/index.html
{% extends "infostatic/base_site.html" %}
{% load i18n %}

{% block content %}    <div id="content-main">
        {% if clnts_list %}
            <ul>
            {% for client in clnts_list %}
                <li>
                <a class="addord" href="{{client.id}}"><strong>{{ client.client_name }}</strong></a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>{% trans 'Client are not available' %}.</p>
        {% endif %}
        <p><a href="/clients/addclient/" class="addlink">{% trans 'Add client' %}</a></p>
    </div>

{% endblock %}

templates/clients/savemsg.html
{% extends "infostatic/base_site.html" %}
{% load i18n %}

{% block content %}
     <p>{{msg}}</p>
{% endblock %}